from django.shortcuts import render
from django.http import HttpResponse, JsonResponse

# Create your views here.
#plain tx response
def text_view(request):
    return HttpResponse(" Welcome to my portfolio")

#html response
def html_view(request):
    return HttpResponse("""
                        
        <html>
        <head>
        <title>My page</title>                
        </head>

                        
        <body>
                 <h1>This is HTML response generated by html_view</h1>       
                 <p>Welcome to your new Django project. Start building your app here 🚀</p>
                 <h2>we can also write css in this . HTML+CSS </h2>
        </body>
                        
        </html>
                    """)


def json_view(request):
    data = {
        #key : value
         
         "name": "QAMARUNNISA HUMERA",
         "language learning": "python",
         "framework using" :"Django",
    }
    return JsonResponse(data)

